gundam:
  card:
    service:
      url: http://localhost:8081/graphql

spring:
  profiles:
    active: debug
  threads:
    virtual:
      enabled: true
  application:
    name: aimuro
#  datasource:
#    url: jdbc:postgresql://localhost:5432/gundam-tcg-rules
#    username: user
#    password: password
#    host-auth-method: trust
  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
    openai:
      api-key: ${OPEN_AI_KEY}
      model: o4-mini
