app:
  ai:
    nomic-prefix: false

spring:
  ai:
    model:
      embedding: ollama
      ollama:
        base-url: http://localhost:11434
        chat:
          options:
            model: qwen2.5:7b-instruct
        embedding:
          options:
            model: qwen3-embedding:0.6b
            truncate: false
        init:
          pull-model-strategy: when_missing
      chat: ollama
      image: none
      audio:
        speech: none
        transcription: none
      moderation: none
